appName: go-app	
appImage: tonopy/go-app:latest
appVersion: v.0.0.0
appReplicas: 1
containerPort: 8080
containerEnvVars:
- name: ENV_VAR_ONE
  value: "valueone"  

servicePort: 8080
serviceType: ClusterIP